# Generated by Django 5.2.1 on 2025-06-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_pets_pet'),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Remainders',
            new_name='Remainder',
        ),
    ]
